name: sigepweb
description: Utilize serviços dos Correios no seu App como buscar CEP ou calcular preços e prazos de encomendas
version: 1.0.3
repository: https://github.com/marcobraghim/sigepweb
issue_tracker: https://github.com/marcobraghim/sigepweb/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  xml2json: ^4.2.0
  dio: ^3.0.9
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.3                     # pub run test
  test_coverage: ^0.4.3             # pub run test_coverage
  # flutter_coverage_badge: ^0.0.1+1  # flutter pub run flutter_coverage_badge
